-- UPDATE 실습

-- D1 인사관리부 > 인사팀으로 변경
UPDATE department2 SET dept_title = '인사팀' WHERE DEPT_ID = 'D1';
-- D3 마케팅부 > 마케팅팀 변경
UPDATE department2 SET DEPT_TITLE = '마케팅팀' WHERE DEPT_ID = 'D3';
-- D8 기술지원부 > 기술지원팀 변경
UPDATE department2 SET DEPT_TITLE = '기술지원팀' WHERE DEPT_ID = 'D8';

--수정된 내용을 저장 COMMIT
-- 되돌리기 ROLLBACK
COMMIT;

--EMPLOYEE2 테이블에서 BONUS를 받지않는사원의 BONUS를 0.1로 변경
UPDATE EMPLOYEE2 SET BONUS = '0.1' WHERE BONUS IS NULL;
--변경 후 EMP_NAME,BONUS 모두 조회
SELECT * FROM EMPLOYEE2;

ROLLBACK;

-- 모든 직원의 기본 급여 인상 EMPLOYEE2
UPDATE department2 SET SALARY = SALARY * 1.1;
SELECT EMP_NAME,SALARY FROM EMPLOYEE2;

-- D9 부서의 모든 직원의 보너스율 0.4로 수정 EMPLOYEE2
UPDATE EMPLOYEE2 SET BONUS = 0.4 WHERE DEPT_CODE = 'D9';

SELECT DEPT_CODE,BONUS FROM EMPLOYEE2;

--DEPT_CODE가 NULL인 직원은 D3부서로 이동
UPDATE EMPLOYEE2 SET DEPT_CODE = 'D3' WHERE DEPT_CODE IS NULL;
SELECT DEPT_CODE FROM EMPLOYEE2;

--특정 입사일 2000-01-01 이후 입사한 직원의 급여 수정 HIRE_DATE
UPDATE EMPLOYEE2 SET SALARY = SALARY * 1.1 WHERE HIRE_DATE > TO_DATE ('2000-01-01' , 'YYYY-MM-DD');
SELECT EMP_NAME,SALARY FROM EMPLOYEE2;
--1997-09-12에 입사한 직원 퇴사처리 ENY_YN
UPDATE EMPLOYEE2 SET ENT_YN = 'Y' WHERE HIRE_DATE = TO_DATE('1997-09-12', 'YYYY-MM-DD');

ROLLBACK;

SELECT EMP_NAME,EMAIL FROM EMPLOYEE2;
-- 특정 도메인 주소 변경
UPDATE EMPLOYEE2
SET EMAIL = REPLACE(EMAIL,'or.kr','KH.KH');
SELECT EMP_NAME,EMAIL FROM EMPLOYEE2;

--핸드폰번호 EMPLOYEE2에서 010뒤에 -붙여서 변경
--LIKE > 무조건 맨 앞이 010이여야하고 중간에 오는  010은 변경 X
UPDATE EMPLOYEE2 SET PHONE = REPLACE(PHONE,'010','010-') WHERE PHONE LIKE '010%';


SELECT PHONE FROM EMPLOYEE2;

--특정 입사일을 가진 직원의 입사일 변경
UPDATE EMPLOYEE2 SET HIRE_DATE = TO_DATE('2000-01-02') WHERE HIRE_DATE = TO_DATE('1999-09-09','YYYY-MM-DD');
SELECT HIRE_DATE FROM EMPLOYEE2;

COMMIT;

SELECT * FROM DEPARTMENT2;
UPDATE DEPARTMENT2
SET DEPT_TITLE = '인사팀';

SELECT * FROM DEPARTMENT2;

--UPDATE 한 번에 여러 컬럼 업데이트

--진행하기전 EMPLOYEE3 만들기 CREAT TEBLE EMPLOYEE 복사
CREATE TABLE EMPLOYEE3 AS SELECT * FROM EMPLOYEE;

-- 200EMP_ID가 200인 직원의 이메일과 전화번호 업데이트
UPDATE EMPLOYEE3 SET EMAIL = 'ONE_SUN@or.kr', PHONE = '01012345678' WHERE EMP_ID = '200';
SELECT EMP_ID,EMAIL,PHONE FROM EMPLOYEE3;

--D9 부서의 모든 직원의 급여 *1.1 보너스 = 0.2 변경
UPDATE EMPLOYEE3 SET SALARY = SALARY * 1.1, BONUS = 0.2 WHERE DEPT_CODE = 'D9';
SELECT * FROM EMPLOYEE3;
--J3 직무 코드를 가진 직원의 직무 코드와 부서코드 변경 J5 D5
UPDATE EMPLOYEE3 SET DEPE_CODE = 'D5' , JOB_CODE = 'J5' WHERE JOB_CODE = 'J3';

--송은희 직원 이름과 이메일 변경 송은휘 SONGSONG@or.kr
UPDATE EMPLOYEE3 SET EMP_NAME = '송은휘', EMAIL = 'SONGSONG@or>kr' WHERE EMP_NAME = '송은희';




