/* JOIN 실습 */

--1. EMPLOYEE 테이블과 DEPARTMENT 테이블을 조인해서
-- 각 직원의 이름과 그 직원이 속한 부서명 조회
SELECT *
FROM EMPLOYEE;
SELECT *
FROM DEPARTMENT;

--ANSI
SELECT EMP_NAME,DEPT_CODE,DEPT_ID
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);

--ORACLE
SELECT EMP_NAME,DEPT_CODE,DEPT_ID
FROM EMPLOYEE , DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;




--2. EMPLOYEE 테이블과 DEPARTMENT 테이블을 조인해서
-- 각 직원의 이름과 그 직원이 속한 부서명,급여 조회
SELECT EMP_NAME,DEPT_CODE,SALARY, DEPT_ID
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);

SELECT EMP_NAME,DEPT_CODE,SALARY, DEPT_ID
FROM EMPLOYEE , DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

--3. EMPLOYEE 테이블과 SAL_GRADE 테이블을 조인해서
-- 각 직원의 이름과 급여 등급 조회
SELECT EMP_NAME, DEPT_CODE, SALARY,EMPLOYEE.SAL_LEVEL
FROM EMPLOYEE
JOIN SAL_GRADE ON (EMPLOYEE.SAL_LEVEL = SAL_GRADE.SAL_LEVEL);
/*다른테이블에서 컬럼명은 다르지만 서로 의미하는 바가 같은 컬럼끼리는 
컬럼명1 = 컬럼명A 사용할수 있지만

다른 테이블에서 컬럼명이 같을 때는 참조하는 테이블이 무엇인지 작성해줘야함
테이블명.컬럼명1 = 테이블명.컬럼명2
*/

SELECT EMP_NAME, DEPT_CODE, SALARY,EMPLOYEE.SAL_LEVEL AS "임플로이", SAL_GRADE.SAL_LEVEL AS "그레이드"
FROM EMPLOYEE ,  SAL_GRADE
WHERE EMPLOYEE.SAL_LEVEL = SAL_GRADE.SAL_LEVEL;

--각 직원의 이름과 그 직원이 속한 부서의 부서명 및 직급 조회
-- 테이블 EMPLOYEE  DEPARTMENT  JOB
--ANSI
SELECT E.EMP_NAME , D.DEPT_TITLE,J.JOB_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE);

/*
E.EMP NAME     D.DEPT TITLE        J.JOB NAME
전지연	         인사관리부	        대리
차태연          	 인사관리부	        대리
방명수	         인사관리부	        사원
*/
--ORACLE
SELECT E.EMP_NAME , D.DEPT_TITLE,J.JOB_NAME
FROM EMPLOYEE E , DEPARTMENT D , JOB J
WHERE E.DEPT_CODE = D.DEPT_ID AND E.JOB_CODE = J.JOB_CODE;

--1. 직원의 이메일 주소와 해당 부서의 부서명 조회
-- TABLE : EMPLOYEE,DEPARTMENT 
-- SELECT EMAIL DEPT_TITLE
--ANSI
SELECT EMAIL , DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);
--ORACLE
SELECT EMAIL , DEPT_TITLE
FROM EMPLOYEE E , DEPARTMENT D 
WHERE E.DEPT_CODE = D.DEPT_ID;


--2. 급여가 300만원 이상인 직원들의 이름과 그 직원이 속한 부서명 조회
-- TABLE : EMPLOYEE,DEPARTMENT
-- SELECT EMP_NAME,DEPT_TITLE
-- WHERE
--ORACLE
SELECT EMP_NAME,DEPT_TITLE
FROM EMPLOYEE E,DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID; AND SALARY > 3000000;

--3. 각 직원의 이름과 그 직원이 속한 부서명의 부서명 급여 등급명 조회
-- TABLE : EMPLOYEE,DEPARTMENT,SAL_GRADE
-- SELECT : EMP_NAME,DEPT_TITLE,SAL_LEVEL
SELECT E.EMP_NAME, D.DEPT_TITLE, S.SAL_LEVEL
FROM EMPLOYEE E, DEPARTMENT D, SAL_GRADE S
WHERE E.DEPT_CODE = D.DEPT_ID AND E.SAL_LEVEL = S.SAL_LEVEL;

--4. 직급이 대리이면서 아시아 지역에 근무하는 직원 조회
-- 사번이름 직급명 부서명 근무지역명 급여를 조회
-- TABLE EMPLOYEE JOB DEPARTMENT LOCATION 
-- SELECT EMPID EMPNAME JOBNAME DEPTTITLE LOCALNAME SALARY 
-- WHERE AND LIKE 조합
--ANSI
SELECT EMP_ID , EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME, SALARY
FROM EMPLOYEE
JOIN DEPARMENT ON (DEPT_CODE = DEPT_ID) ,
JOIN JOB ON (DEPT_CODE = JOB_CODE) AND
LOCATION (DEPT_CODE = LOCAL_CODE);
--ORACLE
SELECT E.EMP_ID , E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE, L.LOCAL_NAME, E.SALARY
FROM EMPLOYEE E , DEPARTMENT D , JOB J , LOCATION L 
WHERE E.DEPT_CODE = D.DEPT_ID AND E.JOB_CODE = J.JOB_CODE AND D.LOCATION_ID = L.LOCAL_CODE AND 
J.JOB_NAME = '대리' AND LOCAL_NAME LIKE 'ASIA%';

--1. D5부서에 속한 직원들의 이름과 직급명 조회
-- 테이블 EMPLOYEE JOB 
SELECT EMP_NAME , JOB_NAME
FROM EMPLOYEE 
JOIN JOB USING(JOB_CODE);

-- 2. 각 부서의 부서명과 해당 부서에 속한 직원의 평균급여 조회
-- 테이블 EMPLOYEE DEPARTMENT
-- GROUP BY
-- AVG
SELECT EMP_NAME , DEPT_ID, DEPT_TITLE, FLOOR(AVG(SALARY))
FROM EMPLOYEE 
GROUP BY DEPT_TITLE 
JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE);

-- 3.급여등급이 S4 이상인 직원의 이름,급여,급여 등급 조회
-- 테이블 EMPLOYEE,SAL_GRADE 
-- WHERE IN
SELECT E.EMP_NAME, E.SALARY, E.SAL_LEVEL
FROM EMPLOYEE E , SAL_GRADE S
WHERE E.SAL_LEVEL = S.SAL_LEVEL
AND S.SAL_LEVEL IN ('S4','S5','S6');