--자동정렬 단축키 컨트롤 + F7
--작성한 시트 모두 실행 F5
--MENU 테이블 생성
CREATE TABLE MENU(
MENU_ID NUMBER(10,0)PRIMARY KEY, --메뉴 ID(기본 키)
MENU_NAME VARCHAR2(100 BYTE), -- 메뉴이름
MENU_DESC VARCHAR2(255 BYTE),
MENU_PRICE NUMBER(10,2)
);


INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_DESC,MENU_PRICE)VALUES(1, '아메리카노','신선한원두로 만든 아메리카노',3000);
INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_DESC,MENU_PRICE)VALUES(2, '카페라떼','부드러운 우유가 들어간 라떼',3500);
INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_DESC,MENU_PRICE)VALUES(3, '카푸치노','진한 커피와 거품이 어우러진 카푸치노',3500);
INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_DESC,MENU_PRICE)VALUES(4, '카라멜 마키아토','달콤한 카라멜 시럽이 들어간 마키아토',4000);
INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_DESC,MENU_PRICE)VALUES(5, '에스프레소','강한 맛과 향의 에스프레소',2500);